name: Build PDF

on:
  push:

jobs:
  build-pdf:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build PDF
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          latexmk_use_xelatex: true

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: kookboek
          path: main.pdf
          retention-days: 30
